// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Home": typeof import("./src/./pages/Home.tsx");
};